// Generated by gencpp from file beckhoff_msgs/CmdRobot.msg
// DO NOT EDIT!


#ifndef BECKHOFF_MSGS_MESSAGE_CMDROBOT_H
#define BECKHOFF_MSGS_MESSAGE_CMDROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <beckhoff_msgs/Vector_q5.h>

namespace beckhoff_msgs
{
template <class ContainerAllocator>
struct CmdRobot_
{
  typedef CmdRobot_<ContainerAllocator> Type;

  CmdRobot_()
    : Timestamp()
    , dq()
    , home_gripper(false)
    , open_gripper(false)
    , close_gripper(false)  {
    }
  CmdRobot_(const ContainerAllocator& _alloc)
    : Timestamp()
    , dq(_alloc)
    , home_gripper(false)
    , open_gripper(false)
    , close_gripper(false)  {
  (void)_alloc;
    }



   typedef ros::Time _Timestamp_type;
  _Timestamp_type Timestamp;

   typedef  ::beckhoff_msgs::Vector_q5_<ContainerAllocator>  _dq_type;
  _dq_type dq;

   typedef uint8_t _home_gripper_type;
  _home_gripper_type home_gripper;

   typedef uint8_t _open_gripper_type;
  _open_gripper_type open_gripper;

   typedef uint8_t _close_gripper_type;
  _close_gripper_type close_gripper;





  typedef boost::shared_ptr< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> const> ConstPtr;

}; // struct CmdRobot_

typedef ::beckhoff_msgs::CmdRobot_<std::allocator<void> > CmdRobot;

typedef boost::shared_ptr< ::beckhoff_msgs::CmdRobot > CmdRobotPtr;
typedef boost::shared_ptr< ::beckhoff_msgs::CmdRobot const> CmdRobotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beckhoff_msgs::CmdRobot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beckhoff_msgs::CmdRobot_<ContainerAllocator1> & lhs, const ::beckhoff_msgs::CmdRobot_<ContainerAllocator2> & rhs)
{
  return lhs.Timestamp == rhs.Timestamp &&
    lhs.dq == rhs.dq &&
    lhs.home_gripper == rhs.home_gripper &&
    lhs.open_gripper == rhs.open_gripper &&
    lhs.close_gripper == rhs.close_gripper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beckhoff_msgs::CmdRobot_<ContainerAllocator1> & lhs, const ::beckhoff_msgs::CmdRobot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beckhoff_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "998ab08fd18737e8efdb2d91fee4e00b";
  }

  static const char* value(const ::beckhoff_msgs::CmdRobot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x998ab08fd18737e8ULL;
  static const uint64_t static_value2 = 0xefdb2d91fee4e00bULL;
};

template<class ContainerAllocator>
struct DataType< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beckhoff_msgs/CmdRobot";
  }

  static const char* value(const ::beckhoff_msgs::CmdRobot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time Timestamp\n"
"Vector_q5 dq\n"
"bool home_gripper\n"
"bool open_gripper\n"
"bool close_gripper\n"
"================================================================================\n"
"MSG: beckhoff_msgs/Vector_q5\n"
"float32 j0\n"
"float32 j1\n"
"float32 j2\n"
"float32 j3\n"
"float32 j4\n"
;
  }

  static const char* value(const ::beckhoff_msgs::CmdRobot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Timestamp);
      stream.next(m.dq);
      stream.next(m.home_gripper);
      stream.next(m.open_gripper);
      stream.next(m.close_gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CmdRobot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beckhoff_msgs::CmdRobot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beckhoff_msgs::CmdRobot_<ContainerAllocator>& v)
  {
    s << indent << "Timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.Timestamp);
    s << indent << "dq: ";
    s << std::endl;
    Printer< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >::stream(s, indent + "  ", v.dq);
    s << indent << "home_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.home_gripper);
    s << indent << "open_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.open_gripper);
    s << indent << "close_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.close_gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BECKHOFF_MSGS_MESSAGE_CMDROBOT_H
