// Generated by gencpp from file beckhoff_msgs/dataArray.msg
// DO NOT EDIT!


#ifndef BECKHOFF_MSGS_MESSAGE_DATAARRAY_H
#define BECKHOFF_MSGS_MESSAGE_DATAARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beckhoff_msgs
{
template <class ContainerAllocator>
struct dataArray_
{
  typedef dataArray_<ContainerAllocator> Type;

  dataArray_()
    : data()  {
      data.assign(0.0);
  }
  dataArray_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0.0);
  }



   typedef boost::array<float, 20>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::beckhoff_msgs::dataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beckhoff_msgs::dataArray_<ContainerAllocator> const> ConstPtr;

}; // struct dataArray_

typedef ::beckhoff_msgs::dataArray_<std::allocator<void> > dataArray;

typedef boost::shared_ptr< ::beckhoff_msgs::dataArray > dataArrayPtr;
typedef boost::shared_ptr< ::beckhoff_msgs::dataArray const> dataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beckhoff_msgs::dataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beckhoff_msgs::dataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beckhoff_msgs::dataArray_<ContainerAllocator1> & lhs, const ::beckhoff_msgs::dataArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beckhoff_msgs::dataArray_<ContainerAllocator1> & lhs, const ::beckhoff_msgs::dataArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beckhoff_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beckhoff_msgs::dataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beckhoff_msgs::dataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beckhoff_msgs::dataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "863ff43db2ffc1168b53b76ab57ce6a3";
  }

  static const char* value(const ::beckhoff_msgs::dataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x863ff43db2ffc116ULL;
  static const uint64_t static_value2 = 0x8b53b76ab57ce6a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beckhoff_msgs/dataArray";
  }

  static const char* value(const ::beckhoff_msgs::dataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[20] data\n"
;
  }

  static const char* value(const ::beckhoff_msgs::dataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beckhoff_msgs::dataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beckhoff_msgs::dataArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BECKHOFF_MSGS_MESSAGE_DATAARRAY_H
