// Generated by gencpp from file beckhoff_msgs/Vector_q5.msg
// DO NOT EDIT!


#ifndef BECKHOFF_MSGS_MESSAGE_VECTOR_Q5_H
#define BECKHOFF_MSGS_MESSAGE_VECTOR_Q5_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beckhoff_msgs
{
template <class ContainerAllocator>
struct Vector_q5_
{
  typedef Vector_q5_<ContainerAllocator> Type;

  Vector_q5_()
    : j0(0.0)
    , j1(0.0)
    , j2(0.0)
    , j3(0.0)
    , j4(0.0)  {
    }
  Vector_q5_(const ContainerAllocator& _alloc)
    : j0(0.0)
    , j1(0.0)
    , j2(0.0)
    , j3(0.0)
    , j4(0.0)  {
  (void)_alloc;
    }



   typedef float _j0_type;
  _j0_type j0;

   typedef float _j1_type;
  _j1_type j1;

   typedef float _j2_type;
  _j2_type j2;

   typedef float _j3_type;
  _j3_type j3;

   typedef float _j4_type;
  _j4_type j4;





  typedef boost::shared_ptr< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> const> ConstPtr;

}; // struct Vector_q5_

typedef ::beckhoff_msgs::Vector_q5_<std::allocator<void> > Vector_q5;

typedef boost::shared_ptr< ::beckhoff_msgs::Vector_q5 > Vector_q5Ptr;
typedef boost::shared_ptr< ::beckhoff_msgs::Vector_q5 const> Vector_q5ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beckhoff_msgs::Vector_q5_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beckhoff_msgs::Vector_q5_<ContainerAllocator1> & lhs, const ::beckhoff_msgs::Vector_q5_<ContainerAllocator2> & rhs)
{
  return lhs.j0 == rhs.j0 &&
    lhs.j1 == rhs.j1 &&
    lhs.j2 == rhs.j2 &&
    lhs.j3 == rhs.j3 &&
    lhs.j4 == rhs.j4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beckhoff_msgs::Vector_q5_<ContainerAllocator1> & lhs, const ::beckhoff_msgs::Vector_q5_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beckhoff_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fa159e5fd623899f47577ffd89d6a4d";
  }

  static const char* value(const ::beckhoff_msgs::Vector_q5_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fa159e5fd623899ULL;
  static const uint64_t static_value2 = 0xf47577ffd89d6a4dULL;
};

template<class ContainerAllocator>
struct DataType< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beckhoff_msgs/Vector_q5";
  }

  static const char* value(const ::beckhoff_msgs::Vector_q5_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 j0\n"
"float32 j1\n"
"float32 j2\n"
"float32 j3\n"
"float32 j4\n"
;
  }

  static const char* value(const ::beckhoff_msgs::Vector_q5_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.j0);
      stream.next(m.j1);
      stream.next(m.j2);
      stream.next(m.j3);
      stream.next(m.j4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector_q5_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beckhoff_msgs::Vector_q5_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beckhoff_msgs::Vector_q5_<ContainerAllocator>& v)
  {
    s << indent << "j0: ";
    Printer<float>::stream(s, indent + "  ", v.j0);
    s << indent << "j1: ";
    Printer<float>::stream(s, indent + "  ", v.j1);
    s << indent << "j2: ";
    Printer<float>::stream(s, indent + "  ", v.j2);
    s << indent << "j3: ";
    Printer<float>::stream(s, indent + "  ", v.j3);
    s << indent << "j4: ";
    Printer<float>::stream(s, indent + "  ", v.j4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BECKHOFF_MSGS_MESSAGE_VECTOR_Q5_H
