set(_CATKIN_CURRENT_PACKAGE "plc_to_pc_pub_cpp")
set(plc_to_pc_pub_cpp_VERSION "0.0.0")
set(plc_to_pc_pub_cpp_MAINTAINER "student <student@todo.todo>")
set(plc_to_pc_pub_cpp_PACKAGE_FORMAT "2")
set(plc_to_pc_pub_cpp_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(plc_to_pc_pub_cpp_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(plc_to_pc_pub_cpp_BUILDTOOL_DEPENDS "catkin")
set(plc_to_pc_pub_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(plc_to_pc_pub_cpp_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(plc_to_pc_pub_cpp_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(plc_to_pc_pub_cpp_TEST_DEPENDS )
set(plc_to_pc_pub_cpp_DOC_DEPENDS )
set(plc_to_pc_pub_cpp_URL_WEBSITE "")
set(plc_to_pc_pub_cpp_URL_BUGTRACKER "")
set(plc_to_pc_pub_cpp_URL_REPOSITORY "")
set(plc_to_pc_pub_cpp_DEPRECATED "")