# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from beckhoff_msgs/catSend.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class catSend(genpy.Message):
  _md5sum = "3e4b9f26ff50bf503fcd6a14b54ee63d"
  _type = "beckhoff_msgs/catSend"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 VelX
float64 VelRot
bool ResetPoz"""
  __slots__ = ['VelX','VelRot','ResetPoz']
  _slot_types = ['float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       VelX,VelRot,ResetPoz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(catSend, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.VelX is None:
        self.VelX = 0.
      if self.VelRot is None:
        self.VelRot = 0.
      if self.ResetPoz is None:
        self.ResetPoz = False
    else:
      self.VelX = 0.
      self.VelRot = 0.
      self.ResetPoz = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2dB().pack(_x.VelX, _x.VelRot, _x.ResetPoz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.VelX, _x.VelRot, _x.ResetPoz,) = _get_struct_2dB().unpack(str[start:end])
      self.ResetPoz = bool(self.ResetPoz)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2dB().pack(_x.VelX, _x.VelRot, _x.ResetPoz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.VelX, _x.VelRot, _x.ResetPoz,) = _get_struct_2dB().unpack(str[start:end])
      self.ResetPoz = bool(self.ResetPoz)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dB = None
def _get_struct_2dB():
    global _struct_2dB
    if _struct_2dB is None:
        _struct_2dB = struct.Struct("<2dB")
    return _struct_2dB
