# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from beckhoff_msgs/CmdTracks.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CmdTracks(genpy.Message):
  _md5sum = "9944d5598f5dddfb3ecdf391f9c85ed5"
  _type = "beckhoff_msgs/CmdTracks"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool stop_tracks
bool start_tracks
float64 linear_vel
float64 rot_vel"""
  __slots__ = ['stop_tracks','start_tracks','linear_vel','rot_vel']
  _slot_types = ['bool','bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stop_tracks,start_tracks,linear_vel,rot_vel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CmdTracks, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stop_tracks is None:
        self.stop_tracks = False
      if self.start_tracks is None:
        self.start_tracks = False
      if self.linear_vel is None:
        self.linear_vel = 0.
      if self.rot_vel is None:
        self.rot_vel = 0.
    else:
      self.stop_tracks = False
      self.start_tracks = False
      self.linear_vel = 0.
      self.rot_vel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2d().pack(_x.stop_tracks, _x.start_tracks, _x.linear_vel, _x.rot_vel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.stop_tracks, _x.start_tracks, _x.linear_vel, _x.rot_vel,) = _get_struct_2B2d().unpack(str[start:end])
      self.stop_tracks = bool(self.stop_tracks)
      self.start_tracks = bool(self.start_tracks)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2d().pack(_x.stop_tracks, _x.start_tracks, _x.linear_vel, _x.rot_vel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.stop_tracks, _x.start_tracks, _x.linear_vel, _x.rot_vel,) = _get_struct_2B2d().unpack(str[start:end])
      self.stop_tracks = bool(self.stop_tracks)
      self.start_tracks = bool(self.start_tracks)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2d = None
def _get_struct_2B2d():
    global _struct_2B2d
    if _struct_2B2d is None:
        _struct_2B2d = struct.Struct("<2B2d")
    return _struct_2B2d
