# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from beckhoff_msgs/CmdRobot.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import beckhoff_msgs.msg
import genpy

class CmdRobot(genpy.Message):
  _md5sum = "998ab08fd18737e8efdb2d91fee4e00b"
  _type = "beckhoff_msgs/CmdRobot"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time Timestamp
Vector_q5 dq
bool home_gripper
bool open_gripper
bool close_gripper
================================================================================
MSG: beckhoff_msgs/Vector_q5
float32 j0
float32 j1
float32 j2
float32 j3
float32 j4"""
  __slots__ = ['Timestamp','dq','home_gripper','open_gripper','close_gripper']
  _slot_types = ['time','beckhoff_msgs/Vector_q5','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Timestamp,dq,home_gripper,open_gripper,close_gripper

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CmdRobot, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Timestamp is None:
        self.Timestamp = genpy.Time()
      if self.dq is None:
        self.dq = beckhoff_msgs.msg.Vector_q5()
      if self.home_gripper is None:
        self.home_gripper = False
      if self.open_gripper is None:
        self.open_gripper = False
      if self.close_gripper is None:
        self.close_gripper = False
    else:
      self.Timestamp = genpy.Time()
      self.dq = beckhoff_msgs.msg.Vector_q5()
      self.home_gripper = False
      self.open_gripper = False
      self.close_gripper = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I5f3B().pack(_x.Timestamp.secs, _x.Timestamp.nsecs, _x.dq.j0, _x.dq.j1, _x.dq.j2, _x.dq.j3, _x.dq.j4, _x.home_gripper, _x.open_gripper, _x.close_gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Timestamp is None:
        self.Timestamp = genpy.Time()
      if self.dq is None:
        self.dq = beckhoff_msgs.msg.Vector_q5()
      end = 0
      _x = self
      start = end
      end += 31
      (_x.Timestamp.secs, _x.Timestamp.nsecs, _x.dq.j0, _x.dq.j1, _x.dq.j2, _x.dq.j3, _x.dq.j4, _x.home_gripper, _x.open_gripper, _x.close_gripper,) = _get_struct_2I5f3B().unpack(str[start:end])
      self.home_gripper = bool(self.home_gripper)
      self.open_gripper = bool(self.open_gripper)
      self.close_gripper = bool(self.close_gripper)
      self.Timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I5f3B().pack(_x.Timestamp.secs, _x.Timestamp.nsecs, _x.dq.j0, _x.dq.j1, _x.dq.j2, _x.dq.j3, _x.dq.j4, _x.home_gripper, _x.open_gripper, _x.close_gripper))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Timestamp is None:
        self.Timestamp = genpy.Time()
      if self.dq is None:
        self.dq = beckhoff_msgs.msg.Vector_q5()
      end = 0
      _x = self
      start = end
      end += 31
      (_x.Timestamp.secs, _x.Timestamp.nsecs, _x.dq.j0, _x.dq.j1, _x.dq.j2, _x.dq.j3, _x.dq.j4, _x.home_gripper, _x.open_gripper, _x.close_gripper,) = _get_struct_2I5f3B().unpack(str[start:end])
      self.home_gripper = bool(self.home_gripper)
      self.open_gripper = bool(self.open_gripper)
      self.close_gripper = bool(self.close_gripper)
      self.Timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I5f3B = None
def _get_struct_2I5f3B():
    global _struct_2I5f3B
    if _struct_2I5f3B is None:
        _struct_2I5f3B = struct.Struct("<2I5f3B")
    return _struct_2I5f3B
