# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from beckhoff_msgs/cmdRobot.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cmdRobot(genpy.Message):
  _md5sum = "4c364234fdb48115e683b6d91edb1a06"
  _type = "beckhoff_msgs/cmdRobot"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 Timestamp
float32[5] Vector_q5"""
  __slots__ = ['Timestamp','Vector_q5']
  _slot_types = ['float32','float32[5]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Timestamp,Vector_q5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cmdRobot, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Timestamp is None:
        self.Timestamp = 0.
      if self.Vector_q5 is None:
        self.Vector_q5 = [0.] * 5
    else:
      self.Timestamp = 0.
      self.Vector_q5 = [0.] * 5

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.Timestamp
      buff.write(_get_struct_f().pack(_x))
      buff.write(_get_struct_5f().pack(*self.Vector_q5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.Timestamp,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 20
      self.Vector_q5 = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.Timestamp
      buff.write(_get_struct_f().pack(_x))
      buff.write(self.Vector_q5.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.Timestamp,) = _get_struct_f().unpack(str[start:end])
      start = end
      end += 20
      self.Vector_q5 = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=5)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
